// <auto-generated />
using System;
using Core.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260414194149_AddInviteAsTeacherToEntryRequest")]
    partial class AddInviteAsTeacherToEntryRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.DAL.Models.BaseUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("OriginalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("BaseUsers");
                });

            modelBuilder.Entity("Core.DAL.Models.EntryRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BaseUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("InviteAsTeacher")
                        .HasColumnType("bit");

                    b.Property<bool>("SentByUniversity")
                        .HasColumnType("bit");

                    b.Property<long>("UniversityId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BaseUserId");

                    b.HasIndex("UniversityId");

                    b.ToTable("EntryRequests");
                });

            modelBuilder.Entity("Core.DAL.Models.StudentEnrollment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BaseUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("UniversityId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.HasIndex("BaseUserId", "UniversityId")
                        .IsUnique();

                    b.ToTable("StudentEnrollments");
                });

            modelBuilder.Entity("Core.DAL.Models.Teacher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BaseUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BaseUserId")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Core.DAL.Models.TeacherEnrollment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BaseUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("UniversityId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.HasIndex("BaseUserId", "UniversityId")
                        .IsUnique();

                    b.ToTable("TeacherEnrollments");
                });

            modelBuilder.Entity("Core.DAL.Models.University", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("DirectorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsOpened")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("Core.DAL.Models.BaseUser", b =>
                {
                    b.OwnsOne("Core.DAL.Models.Address", "Address", b1 =>
                        {
                            b1.Property<long>("BaseUserId")
                                .HasColumnType("bigint");

                            b1.Property<string>("City")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Country")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Street")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("BaseUserId");

                            b1.ToTable("BaseUsers");

                            b1.WithOwner()
                                .HasForeignKey("BaseUserId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Core.DAL.Models.EntryRequest", b =>
                {
                    b.HasOne("Core.DAL.Models.BaseUser", "BaseUser")
                        .WithMany("EntryRequests")
                        .HasForeignKey("BaseUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.DAL.Models.University", "University")
                        .WithMany("EntryRequests")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseUser");

                    b.Navigation("University");
                });

            modelBuilder.Entity("Core.DAL.Models.StudentEnrollment", b =>
                {
                    b.HasOne("Core.DAL.Models.BaseUser", "BaseUser")
                        .WithMany("StudentEnrollments")
                        .HasForeignKey("BaseUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.DAL.Models.University", "University")
                        .WithMany("StudentEnrollments")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseUser");

                    b.Navigation("University");
                });

            modelBuilder.Entity("Core.DAL.Models.Teacher", b =>
                {
                    b.HasOne("Core.DAL.Models.BaseUser", "BaseUser")
                        .WithOne("Teacher")
                        .HasForeignKey("Core.DAL.Models.Teacher", "BaseUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseUser");
                });

            modelBuilder.Entity("Core.DAL.Models.TeacherEnrollment", b =>
                {
                    b.HasOne("Core.DAL.Models.BaseUser", "BaseUser")
                        .WithMany("TeacherEnrollments")
                        .HasForeignKey("BaseUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.DAL.Models.University", "University")
                        .WithMany("TeacherEnrollments")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseUser");

                    b.Navigation("University");
                });

            modelBuilder.Entity("Core.DAL.Models.University", b =>
                {
                    b.HasOne("Core.DAL.Models.BaseUser", "Director")
                        .WithMany("DirectingUniversities")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Core.DAL.Models.Address", "Address", b1 =>
                        {
                            b1.Property<long>("UniversityId")
                                .HasColumnType("bigint");

                            b1.Property<string>("City")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Country")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Street")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("UniversityId");

                            b1.ToTable("Universities");

                            b1.WithOwner()
                                .HasForeignKey("UniversityId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("Core.DAL.Models.BaseUser", b =>
                {
                    b.Navigation("DirectingUniversities");

                    b.Navigation("EntryRequests");

                    b.Navigation("StudentEnrollments");

                    b.Navigation("Teacher");

                    b.Navigation("TeacherEnrollments");
                });

            modelBuilder.Entity("Core.DAL.Models.University", b =>
                {
                    b.Navigation("EntryRequests");

                    b.Navigation("StudentEnrollments");

                    b.Navigation("TeacherEnrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
