apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim-auth
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim-core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim-courses
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim-forums
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
 