syntax = "proto3";

option csharp_namespace = "UserService";

service GrpcUsers {
    rpc GetInfoForTopic (GetInfoRequest) returns (GrpcTopicInfoModel);
    rpc GetUniversityName (UniversityId) returns (UniversityName);
    rpc GetUserName (UserId) returns (UserName);
    rpc GetUserUniversityRole (UserUniversityRequest) returns (UserUniversityRole);
}

message GetInfoRequest {
    string universityName = 1;
    string useremail = 2;
}

message GrpcTopicInfoModel {
    int64 universityId = 1;
    int64 userId = 2;
    bool isAllowed = 3;
    bool isTeacher = 4;
    bool isDirector = 5;
}

message UniversityName {
    string universityName = 1;
}

message UniversityId {
    int64 universityId = 1;
}

message UserName{
    string username = 1;
}

message UserId{
    int64 userId = 1;
}

message UserUniversityRequest {
    int64 userId = 1;
    int64 universityId = 2;
}

message UserUniversityRole {
    string role = 1;
}